---
booktitle: Proceedings of The 25th International Conference on Artificial Intelligence
  and Statistics
shortname: AISTATS
volume: '151'
year: '2022'
start: 2022-03-28
end: 2022-03-30
published: 2022-05-03
conference_number: '25'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: AISTATS-2022
month: 0
cycles: false
bibtex_editor: Camps-Valls, Gustau and Ruiz, Francisco J. R. and Valera, Isabel
editor:
- given: Gustau
  family: Camps-Valls
- given: Francisco J. R.
  family: Ruiz
- given: Isabel
  family: Valera
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 25th International Conference on Artificial Intelligence and Statistics
    Held in A Virtual Conference on 28-30 March 2022

  Published as Volume 151 by the Proceedings of Machine Learning Research on 03 May 2022.

  Volume Edited by:
    Gustau Camps-Valls
    Francisco J. R. Ruiz
    Isabel Valera

  Series Editors:
    Neil D. Lawrence
date_str: 28--30 Mar
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v151"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v151
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v151
email: ''
conference:
  name: International Conference on Artificial Intelligence and Statistics
  url: https://aistats.org/aistats2022/index.html
  location: A Virtual Conference
  dates:
  - 2022-03-28
  - 2022-03-29
  - 2022-03-30
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v151/aistats22.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v151/aistats22.bib
